### ISSUE TITLE
missing "explorer mode" docs?

### ISSUE THREAD

**Issue by andrewhw** [replit/replit.github.io#102]
On the webpage at https://docs.repl.it/misc/annotations there is a link to a page about "explorer mode" -- but it doesn't exist.

**Comment by sixhobbits** [comment]
Thanks for noticing - I'll add that page. In the meantime https://repl.it/talk/announcements/Become-an-Explorer/6180 has some details on Explorer Mode if you need them.

**Comment by sixhobbits** [comment]
added - note that there are also more docs about the annotations here that are more up to date https://docs.repl.it/Teams/Annotations - will do some more restructuring to merge these pages.
