### ISSUE TITLE
Update Secrets Tutorial

### ISSUE THREAD

**Issue by BD103** [replit/replit.github.io#145]
Please upgrade the secrets tutorial on `.env` files with the latest Replit update.

**Comment by sixhobbits** [comment]
The .env update is still only for explorers I think? 

But we will definitely ship an update when its GA

**Comment by BD103** [comment]
Ah, that makes sense. Thanks!

**Comment by BD103** [comment]
Also, could you mention that secrets are only applied when using the run button? I found that trying to get secrets through the shell does not work.

**Comment by sixhobbits** [comment]
Thanks for this - yep it only works with the run button for now. The shell
integration with environment variables might be supported in the future -
we'll update the docs to reflect that.
