### ISSUE TITLE
Mention that host must be 0.0.0.0

### ISSUE THREAD

**Issue by ad-si** [replit/replit.github.io#168]
I just tried to serve a Parcel development server via replit, and it only seems to work if i set `host=0.0.0.0`. However, this is not explicitly mentioned on https://docs.replit.com/repls/http-servers

**Comment by RayhanADev** [comment]
In addition to the above:
> Hosting on 0.0.0.0 means Replit will automagically detect your project is running a webserver and open a webview window and hosting urls. Otherwise you may end up running your project in a VNC window!

Could use some cleaning up but it gets the point across.

**Comment by sixhobbits** [comment]
thanks, fixed in https://github.com/replit/replit.github.io/pull/227
