### ISSUE TITLE
Repl.it github sign-in not working

### ISSUE THREAD

**Issue by Variable-X** [replit/replit.github.io#25]
IDK if this is the right place to open an issue, but I can't sign in!
When I try to sign in with Github, the sign-in tab closes and Repl.it says: something went wrong. I'm fairly sure this is on Repl's side because when I try several times, Github makes me reauthorize Repl, so Github is at least registering the attempts.

**Comment by timmyichen** [comment]
A few questions:

Is this a new development?  e.g. do you already have a repl.it account, but you are no longer able to sign into it?  If yes, can you email me at tim@repl.it with the email associated with your account?  Or are you trying to register a new account?

**Comment by NLuca** [comment]
I have the same problem and I am not able to login with Repl.it after signing in with GitHub. What can I do?
Thanks.

**Comment by TheMysteryOfCode** [comment]
@timmyichen hey! I am also facing a similar issue. When I try to make a new account using GitHub on replit.com, it tries to verify, then shows a screen, "Authentication failed, please try again later. I have been trying to register an account on replit using GitHub for the past 1 month, without success. Please help me.

**Comment by jadewarrior1121** [comment]
One thing that worked for me is that i go to site settings and reset the cookies for repl.it and github, let me know if it works for you guys!

**Comment by infokilo** [comment]
Same issue here. I get the message when using Safari on iOS 11. However, it works fine when I use a desktop.
