### ISSUE TITLE
Weird behavior on some tests

### ISSUE THREAD

**Issue by davidauza-engineer** [replit/replit.github.io#27]
Hi

I was working on an exercise and I got the following results while trying to pass the test cases:

![Screenshot 1](https://p19.zdusercontent.com/attachment/9304358/nrPS4M7okFrPg2vMPck3W1c6g?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..TKzUqAVFS1rgicejukiuBg.wMuTPj8PXVhmPqmXNBI5TPV2cFjjrt4tBsujRJZPgmvd4_xjE4710XMQVIxuvBo5K1j7vW-wYuetB0gsE1R0NlXtb7AQyuZZFL0VOiz9KfwJ8D82F6hwMPKz-1nRwVsjc1ZycExzVAnk_2VMi3-AcOO9fD7wWjPe5J97_Gq_kTdNxsMGV5oWeIIofiFuV0hPD62rf88vJXF7fcnLZZa5Qp9AQAanTlXh0n_Ejh3z7Z2qERvJ_ux_89NtSGP3I5QMPtRdzxD7HAN_RAhE2H-zpQ50VHBzAKk8G-7JvpzWq8k.rIBtnrhLW-oq2_xj5uB-sg)

![Screenshot 2](https://p19.zdusercontent.com/attachment/9304358/vHR10yBje2qnddMKi28ZGVa52?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..prIVFj2QAHzTcB9Auz2zew.l71cQSjZugzhEuZ1fogW8HEAIDprliOS9xxCPuT-Pb27xWrljneeLDInlw2TER_nH54-Rbumlo6WN-dg-aRy3iv22i5pbGpFmgF7SVJBXibJnUG65_6NIK98ir6lBX6EcSrhtVdn50WVuCw1_eGiJ4km-wBndsyjwhN0fOp8KVxWEw78sFaL21k_UYqfYMaNEUuh2W_FL0F_e1yFqhCm6cuAda1xmxNs-F_r_qLGWB3Fgg_Zt0xt0LwCy9w3K_Rub7l3c6tLHSkwsUwKYX_kCTnM9ElfPsMcUl6cnlLkW-k.YRfp76CH_RDlPi4wdkwgOg)

This is something weird as it shows that I pass the test cases, but still shows a failed message. As you can see, when I click What's wrong nothing is displayed in the failed tests section.

The exercise can be found [here](https://repl.it/student/submissions/8793799).

It is called Insertion Sort Itself and it is under the Algorithms & Data Structures Ruby section.

The code I'm using is:

```ruby
def sort_itself(array)
  # write your code here
  array_length = array.length
  i = 0
  while i < array_length - 1
    current_number = array[i]
    next_number = array[i + 1]
    if !(current_number < next_number)
      number_to_order = next_number
      j = i + 1
      while j > 0
        if number_to_order > array[j - 1] && number_to_order < array[j]
          array[j] = number_to_order
          break
        else
          array[j] = array[j - 1]
        end
        if j == 1
          array[i - 1] = number_to_order
        end
        j -= 1
      end
    end
    puts array.join(' ')
    i += 1
  end
end

sort_itself([1, 4, 3, 6, 9, 2])
# => 1 4 3 6 9 2
#    1 3 4 6 9 2
#    1 3 4 6 9 2
#    1 3 4 6 9 2
#    1 2 3 4 6 9
```

Please let me know if you need further details or if I need to do something else.

Thanks,

Regards,

David Auza

**Comment by davidauza-engineer** [comment]
Hi

I changed my code and now it passes all the test cases with no issues. I think the problem was related to my algorithm not doing the right job. However, you guys may want to check what's happening, so next time students receive appropriate feedback according to its code.

Below you can find the new code that passes all the test cases:

```ruby
def sort_itself(array)
  # write your code here
  i = 0
  array_length = array.length
  # loop from left to right
  while i < array_length - 1
    current_number = array[i]
    next_index = i + 1
    next_number = array[i + 1]
    if current_number > next_number
      j = next_index
      # loop from right to left
      while j > 0
        actual_number = array[j]
        previous_number = array[j - 1]
        if actual_number < previous_number
          # swap the values
          array[j - 1] = actual_number
          array[j] = previous_number
        end
        j -= 1
      end
    end
    puts array.join(' ')
    i += 1
  end
end

sort_itself([1, 4, 3, 6, 9, 2])
# => 1 4 3 6 9 2
#    1 3 4 6 9 2
#    1 3 4 6 9 2
#    1 3 4 6 9 2
#    1 2 3 4 6 9
```

Regards,

David Auza

**Comment by kodumbeats** [comment]
Hi David, I'm happy to read you were able to solve your issue. In the future, please direct bug reports to https://replit.canny.io/bug-reports.
