### ISSUE TITLE
Repl.it github sign-in not working 

### ISSUE THREAD

**Issue by NLuca** [replit/replit.github.io#50]
I was trying to open an account using my GitHub credential but I'm not able to login Repl.it.
I'm stuck with email and password and I can not proceed ahead.
What can I do?

**Comment by davidionita** [comment]
This was probably due to some of GitHub's services being down yesterday (OAuth was also affected most likely).  Looks like everything is operating normally again, so you should be able to log in using GitHub now.

GitHub Status:  [https://www.githubstatus.com/](https://www.githubstatus.com/)

**Comment by amasad** [comment]
should be working now! let me know if it's not
