### ISSUE TITLE
Add Repl Auth Docs

### ISSUE THREAD

**Issue by Obaida-Albaroudi** [replit/replit.github.io#86]
https://repl.it/@util/replit-docs-obaidaa#README.md

**Comment by turbio** [comment]
unbooping since uh... booped issues break boops

**Comment by sixhobbits** [comment]
@Obaida-Albaroudi - I wanted to merge that auth tutorial in but the link 404s for me now. Do you still have it?

**Comment by Obaida-Albaroudi** [comment]
@sixhobbits I think I ended up deleting the file on accident. Let me remake it and make another PR, thanks for checking on this.

**Comment by sixhobbits** [comment]
@Obaida-Albaroudi - If I remember correctly, it was basically the same as https://repl.it/talk/learn/Authenticating-users-with-Replit-Auth/23460 right? If yes, I can get this edited and added as a page in docs.

**Comment by Obaida-Albaroudi** [comment]
@sixhobbits yup this is correct!! Thanks for the help here Gareth!

**Comment by Obaida-Albaroudi** [comment]
@sixhobbits I have more free time towards the end of the week, I can get to it again if you have not already!

**Comment by sixhobbits** [comment]
live :) https://docs.repl.it/repls/repl-auth
